name: first_one
on: 
    push

jobs:
     hello:
        runs-on: ubuntu-latest
        steps:
        -name: Echo current branch
        -run: encho "$(date):current branch is $((github.ref_name))"

        -name: Checkout source
         uses: actions/checkout@v2


